### ISSUE TITLE
Need Help With Error Message

### ISSUE THREAD

**Issue by davidbeauchesne** [fabytm/Outage-Detector#8]
I am new to Python and need help with Outage-Detector (OD).
Installation is to a Raspberry Pi Zero with a fresh Buster installation (May 2020).
These are the steps I followed to install OD:
     sudo apt update
     sudo apt full-upgrade
     sudo reboot
The above steps were not necessary as the Raspberry Pi OS performs them automatically with the initial setup.
     sudo apt-get install python3-pip
     sudo apt-get install python3-venv
     cd ~
     python3 -m venv od_venv     # (o)utage (d)etector (v)irtual (env)ironment
     source od_venv/bin/activate
At this point, the Bash prompt has changed to show that the virtual environment is active.
     pip3 install Outage-Detector
     outage_detector --init
Initialization appeared successful.  I selected "mail" and immediately received an email test message.
I also selected "y"es to cron.  An examination of the pi user's cron files show the additions have been made for OD.

To test, I shutdown the Pi for 10 minutes.  After restarting, I received no email.  The errors.txt file in ~/.config/outagedetector contains:

  File "/home/pi/od_venv/bin/outage_detector", line 10, in <module>
    sys.exit(main())
  File "/home/pi/od_venv/lib/python3.7/site-packages/outagedetector/__main__.py", line 20, in main
    outage.check_power_and_internet(args.run, args.notify)
  File "/home/pi/od_venv/lib/python3.7/site-packages/outagedetector/outage_detector.py", line 111, in check_power_and_internet
    last_periodicity = int(file_data[3])
ValueError: invalid literal for int() with base 10: '4led'

What step(s) have I missed?  What did I do wrong?

Thanks!

David B.

**Comment by fabytm** [comment]
Hi, I haven't seen my package throw this error yet. Could you show me what's inside the last_timestamp.txt file? (this should be in the same folder as the errors.txt file)

**Comment by davidbeauchesne** [comment]
Unfortunately, I did not keep the file.  Since it was not working and I had not received a response to my query, I tried a couple more times to re-install everything.  I am now getting different Python complaints about push bullet(sp?) even though I selected mail as the notification type.

Two questions:
(1) When the Pi reboots, the Python virtual environment is no longer active.  Is that a problem?
(2) What will happen to the integrity of the timestamp file -- or any of the configuration files -- if power is lost when the file is being written? Could this be the cause of the bad data field in my initial query?  Should the scripts be able to handle damaged or incomplete configuration files?

Note that I have ordered another Pi and will not return to testing this for a number of days.  When I have the new one setup, I will report back to you on any suggestions you make.

David

**Comment by dioncm-code** [comment]
Hi - I have the exact same issue as David i.e. after having completed the set-up and having received a confirmation email, once I unplug the raspberry pi, I do not get an email to inform me of power down.  I also notice that the venv is not active once the pi reboots.  here is what I have in my last_timestamp:

07-07-2020 20-30-02,07-07-2020 20-30-02,scheduled,0

**Comment by fabytm** [comment]
@davidbeauchesne @dioncm-code 

1) The virtual environment doesn't have to be active after a reboot. When scheduling the script to run automatically, it already uses the python interpreter from the virtual environment.
2) This is something I've been thinking about but I never encountered an issue with it (and I do get a fair share of power outages). It is something that will have to be handled.

@dioncm-code Could you send me the contents of the errors.txt file?

**Comment by dioncm-code** [comment]
Hi - the errors.txt file is actually empty.  Do you have any suggestions of things I can try to fix it - are there any settings in the raspberry pi configuration and enable this?  Should I install PIP3?  Should I do a clean install of Rasbian and retry?

Thank you - this program is great and I can wait to be able to monitor my power outage

**Comment by fabytm** [comment]
Sorry for the delay, there is a way to test if it is working. With the virtual environment activated, execute the following: "outage_detector --run boot --notify {whichever option you chose (mail/notification/ifttt)}.

This triggers the script to send a message (it should tell you there's been a power outage).

**Comment by davidbeauchesne** [comment]
I have had time to look at this again.  New Raspberry Pi.  New installation of Buster.  Used the same instructions for setup as in my June 29th posting.
Configured for mail.  Learned that gmail.com will not work on port 587 (as does my email client) but it does work on port 465.  I received the email test message.  I tested and got this error message:

(od_venv) pi@outage-detector:~ $ outage_detector --run boot --notify mail
Power was out for 0 to 0 minutes at 13-08-2020 12-05-23
Traceback (most recent call last):
  File "/home/pi/od_venv/bin/outage_detector", line 10, in <module>
    sys.exit(main())
  File "/home/pi/od_venv/lib/python3.7/site-packages/outagedetector/__main__.py", line 20, in main
    outage.check_power_and_internet(args.run, args.notify)
  File "/home/pi/od_venv/lib/python3.7/site-packages/outagedetector/outage_detector.py", line 149, in check_power_and_internet
    push.push_to_iOS("Power outage", notification, push_key)
  File "/home/pi/od_venv/lib/python3.7/site-packages/outagedetector/pushnotification.py", line 6, in push_to_iOS
    pb = PushBullet(pb_key)
  File "/home/pi/od_venv/lib/python3.7/site-packages/pushbullet/pushbullet.py", line 43, in __init__
    self.refresh()
  File "/home/pi/od_venv/lib/python3.7/site-packages/pushbullet/pushbullet.py", line 381, in refresh
    self._load_devices()
  File "/home/pi/od_venv/lib/python3.7/site-packages/pushbullet/pushbullet.py", line 78, in _load_devices
    resp_dict = self._get_data(self.DEVICES_URL)
  File "/home/pi/od_venv/lib/python3.7/site-packages/pushbullet/pushbullet.py", line 67, in _get_data
    raise InvalidKeyError()
pushbullet.errors.InvalidKeyError

Is this a script error?  I requested an email test yet it looks like it is trying to use Pushbullet.

David B.

**Comment by rotv** [comment]
Yes, it's a script bug preventing the "alarm emails". See pull request #14

**Comment by sgrayban** [comment]
Just saw I am also having this issue

```
# cat /root/.config/outagedetector/last_timestamp.txt 
26-07-2021 01-06-10,15-07-2021 16-40-03,boot,1led,4
```

```
# /usr/bin/python3 /usr/local/bin/outage_detector --run scheduled --notify notification
Traceback (most recent call last):
  File "/usr/local/bin/outage_detector", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/outagedetector/__main__.py", line 20, in main
    outage.check_power_and_internet(args.run, args.notify)
  File "/usr/local/lib/python3.7/dist-packages/outagedetector/outage_detector.py", line 111, in check_power_and_internet
    last_periodicity = int(file_data[3])
ValueError: invalid literal for int() with base 10: '1led'
```
Was there a fix for this?

**Comment by rotv** [comment]
Seems to be garbage in your file, I suggest you delete last_timestamp.txt and try again.

**Comment by sgrayban** [comment]
That was it... thanks!

**Comment by davidbeauchesne** [comment]
The latest version of the code fixes this.  Closing.
